
import { Trip } from '../types';

export const generateTripKML = (trip: Trip) => {
  // XML Header
  let kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${trip.settings.name}</name>
    <description>Generated by NomadFlow</description>
    <Style id="dayPin">
      <IconStyle>
        <scale>1.1</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/red-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
`;

  // Iterate Days
  trip.itinerary.forEach((day, index) => {
    const dayDate = new Date(day.id).toLocaleDateString();
    
    // Create a Folder for each day
    kml += `    <Folder>
      <name>Day ${index + 1} (${dayDate})</name>
`;

    day.activities.forEach((act) => {
      // Only add activities that have a location or flight details
      let location = act.location;
      let name = act.title;
      let description = `${act.time} ${act.notes || ''}`;

      if (act.type === 'FLIGHT' && act.flightDetails) {
          location = `${act.flightDetails.departure.city} Airport`;
          name = `Flight: ${act.flightDetails.airline} ${act.flightDetails.flightNumber}`;
          description = `Dep: ${act.flightDetails.departure.time} (${act.flightDetails.departure.terminal || '-'})`;
      }

      if (location) {
        // Escape special chars for XML
        const cleanName = name.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
        const cleanDesc = description.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
        const cleanLoc = location.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

        kml += `      <Placemark>
        <name>${cleanName}</name>
        <description>${cleanDesc}</description>
        <address>${cleanLoc}</address>
        <styleUrl>#dayPin</styleUrl>
      </Placemark>
`;
      }
    });

    kml += `    </Folder>
`;
  });

  kml += `  </Document>
</kml>`;

  // Create Blob and Download
  const blob = new Blob([kml], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `NomadFlow_${trip.settings.name}.kml`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
